# Generated by Django 5.2.2 on 2026-05-03 22:36

import a_Site.services.imagem_service
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.SlugField(choices=[('', 'Selecione o tipo de conteúdo'), ('ATPagina', 'Páginas'), ('ATNoticia', 'Notícias'), ('ATInforme', 'Informes'), ('ATLink', 'Links'), ('ATImagem', 'Imagens'), ('ATBanner', 'Banners'), ('ATEvento', 'Eventos'), ('ATAgenda', 'Agendas'), ('ATArquivo', 'Arquivo'), ('ATServico', 'Serviço'), ('ATView', 'Visão')], max_length=20, unique=True)),
                ('descricao', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de Conteúdo',
                'verbose_name_plural': 'Tipos de conteúdos',
                'db_table': 'portalufopa_contenttype',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.SlugField(max_length=150, unique=True)),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, default=None, null=True, verbose_name='Breve descrição')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('update_at', models.DateField(auto_now=True, verbose_name='Data de atualização')),
                ('status', models.BooleanField(blank=True, choices=[(False, 'Site Bloqueado'), (True, 'Site Ativo')], default=True, null=True)),
                ('facebook_link', models.URLField(blank=True, default=None, max_length=255, null=True)),
                ('twitter_link', models.URLField(blank=True, default=None, max_length=255, null=True)),
                ('youtube_link', models.URLField(blank=True, default=None, max_length=255, null=True)),
                ('google_link', models.URLField(blank=True, default=None, max_length=255, null=True)),
                ('flicker_link', models.URLField(blank=True, default=None, max_length=255, null=True)),
                ('rss_link', models.URLField(blank=True, default=None, max_length=255, null=True)),
                ('logo', models.ImageField(blank=True, default=None, null=True, upload_to=a_Site.services.imagem_service.ImagemService.content_file_imagem_site, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Logo do site')),
                ('banner_topo', models.ImageField(blank=True, default=None, null=True, upload_to=a_Site.services.imagem_service.ImagemService.content_file_imagem_site, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Banner de destaque')),
                ('favicon', models.ImageField(blank=True, default=None, null=True, upload_to=a_Site.services.imagem_service.ImagemService.content_file_imagem_site, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Favicon')),
                ('texto_rodape', models.TextField(blank=True, default=None, null=True)),
                ('facebook_cod', models.TextField(blank=True, default=None, null=True)),
                ('twitter_cod', models.TextField(blank=True, default=None, null=True)),
                ('youtube_cod', models.TextField(blank=True, default=None, null=True)),
                ('google_cod', models.TextField(blank=True, default=None, null=True)),
                ('flicker_cod', models.TextField(blank=True, default=None, null=True)),
                ('analytic_cod', models.TextField(blank=True, default=None, null=True)),
                ('html_cod', models.TextField(blank=True, default=None, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=255, null=True)),
                ('telefone', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('workflow', models.CharField(choices=[('Privado', 'Privado'), ('Publico', 'Publico')], default='Privado', max_length=20)),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criados_por_mim', to=settings.AUTH_USER_MODEL)),
                ('tipos_conteudo', models.ManyToManyField(related_name='sites_vinculados', to='a_Site.contenttype')),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
                'db_table': 'portalufopa_site',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.SlugField(max_length=150)),
                ('titulo', models.CharField(max_length=150)),
                ('imagem', models.ImageField(upload_to=a_Site.services.imagem_service.ImagemService.content_file_imagem, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('update_at', models.DateField(auto_now=True, verbose_name='Data de atualização')),
                ('status', models.BooleanField(default=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='a_Site.site')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'db_table': 'portalufopa_tag',
            },
        ),
    ]
