# Generated by Django 5.2.2 on 2026-05-05 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_Site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='site',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de atualização'),
        ),
    ]
