# Generated by Django 5.2.2 on 2026-05-09 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_Site', '0003_alter_contenttype_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenttype',
            name='tipo',
            field=models.SlugField(choices=[('', ''), ('ATPagina', 'Páginas'), ('ATNoticia', 'Notícias'), ('ATPasta', 'Pasta'), ('ATInforme', 'Informes'), ('ATLink', 'Links'), ('ATImagem', 'Imagens'), ('ATBanner', 'Banners'), ('ATEvento', 'Eventos'), ('ATAgenda', 'Agendas'), ('ATArquivo', 'Arquivo'), ('ATServico', 'Serviço'), ('ATView', 'Visão')], max_length=20, unique=True),
        ),
    ]
