# Generated by Django 5.2.2 on 2026-05-03 22:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('a_Site', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('level', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Papel',
                'verbose_name_plural': 'Papéis',
                'db_table': 'a_acl_role',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('login_success', 'Login com sucesso'), ('login_failed', 'Tentativa de login falha'), ('logout_success', 'Logout com sucesso'), ('register_success', 'Registro de novo usuário'), ('register_send_email_activate', 'Email de ativação de conta enviado'), ('register_activate', 'Registro de usuário ativado com sucesso'), ('register_activate_failed', 'Link de ativação inválido ou expirado'), ('2fa_token_sent', 'Token 2FA enviado'), ('2fa_validated', 'Token 2FA validado'), ('password_reset_requested', 'Solicitação de redefinição de senha'), ('password_reset_done', 'Senha redefinida'), ('password_changed', 'Senha alterada'), ('permissions_changed', 'Permissões ou grupos alterados')], max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes', to='a_Site.contenttype')),
            ],
            options={
                'verbose_name': 'Permissão',
                'verbose_name_plural': 'Permissões',
                'db_table': 'a_acl_permission',
            },
        ),
        migrations.CreateModel(
            name='SiteRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.ManyToManyField(related_name='atribuidas_em_sites', to='a_Acl.permission')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros_roles', to='a_Site.site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Papel no Site',
                'verbose_name_plural': 'Papéis nos Sites',
                'db_table': 'a_acl_siterole',
                'unique_together': {('user', 'site')},
            },
        ),
    ]
