# Generated by Django 5.2.2 on 2026-05-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_Acl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siterole',
            name='permissions',
            field=models.ManyToManyField(related_name='permissoes_em_sites', to='a_Acl.permission'),
        ),
        migrations.AlterField(
            model_name='siterole',
            name='roles',
            field=models.ManyToManyField(related_name='atribuidas_em_sites', to='a_Acl.role'),
        ),
    ]
