# Generated by Django 5.2.2 on 2026-05-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_Acl', '0002_siterole_permissions_alter_siterole_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permissons',
            field=models.ManyToManyField(related_name='atribuidos_em_role', to='a_Acl.permission'),
        ),
    ]
