# Generated by Django 5.2.2 on 2026-05-04 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_Acl', '0003_role_permissons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='permissons',
            new_name='permissions',
        ),
    ]
