upstream django {
    server 127.0.0.1:8000;
}

server {
    listen 443 ssl;

    client_max_body_size 5000m;

    ssl_certificate /apps/mamba/icpedu/www.ufopa.edu.br.crt;
	ssl_certificate_key /apps/mamba/icpedu/www.ufopa.edu.br.key;

    autoindex off;


    location /static/ {
        alias /home/mamba/staticfiles/static/;
    }

    location /media/{
        alias /home/mamba/staticfiles/media/;
    }

    location / {
        # adicionar configuração do django aqui.
        proxy_pass http://django;

        # Cabeçalhos recomendados
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # Evita redirecionamentos automáticos indesejados
        proxy_redirect off;
    }
}
