[supervisord]
childlogdir = /var/log/supervisor
logfile = /var/log/supervisor/supervisord.log
logfile_maxbytes = 50MB
logfile_backups = 10
loglevel = info
pidfile = /var/run/supervisord.pid
umask = 022
nodaemon = true
nocleanup = false

[inet_http_server]
port = 9001
username = adminsite
password = ?_mamba_negra_em_perigo__@_2025

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl = http://localhost:9001
username = adminsite
password = ?_mamba_negra_em_perigo__@_2025

[program:mamba]
command=gunicorn --chdir /apps/mamba core.wsgi --workers 10 --threads 10 --worker-class gthread --bind 0.0.0.0:8000 --timeout 300 --max-requests 1000 --max-requests-jitter 100 
process_name=mamba
autostart=true
startretries=5
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/supervisor/mamba.out.log
stderr_logfile=/var/log/supervisor/mamba.err.log
stdout_logfile_maxbytes=20MB
stderr_logfile_maxbytes=20MB
priority=1


[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
process_name=nginx
directory=/etc/nginx
priority=10