# Generated by Django 5.2.2 on 2026-05-06 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('a_Site', '0003_alter_contenttype_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.SlugField(max_length=255)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, default=None, null=True)),
                ('corpo', models.TextField(blank=True, default=None, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('public_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Data de publicacção')),
                ('workflow', models.CharField(choices=[('Privado', 'Privado'), ('Publico', 'Publico')], default='Privado', max_length=20)),
                ('tipo', models.CharField(choices=[('', ''), ('ATPagina', 'Páginas'), ('ATNoticia', 'Notícias'), ('ATInforme', 'Informes'), ('ATLink', 'Links'), ('ATImagem', 'Imagens'), ('ATBanner', 'Banners'), ('ATEvento', 'Eventos'), ('ATAgenda', 'Agendas'), ('ATArquivo', 'Arquivo'), ('ATServico', 'Serviço'), ('ATView', 'Visão')], max_length=20)),
                ('show_in_menu', models.BooleanField(default=True)),
                ('excluir_nav', models.BooleanField(default=False)),
                ('path', models.CharField(max_length=255, unique=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('dono', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='a_Content.content')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_Site.site')),
            ],
            options={
                'verbose_name': 'Catalago de conteúdo',
                'verbose_name_plural': 'Catalagos de conteúdos',
                'db_table': 'catalog_content',
                'ordering': ['titulo'],
                'unique_together': {('site', 'url')},
            },
        ),
    ]
