# Generated by Django 5.2.2 on 2026-05-06 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_Content', '0001_initial'),
        ('a_Site', '0003_alter_contenttype_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='path',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='content',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogs', to='a_Site.site'),
        ),
    ]
