# Generated by Django 5.2.2 on 2026-05-09 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_Content', '0002_alter_content_path_alter_content_site'),
        ('a_Site', '0004_alter_contenttype_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='tipo',
            field=models.CharField(choices=[('', ''), ('ATPagina', 'Páginas'), ('ATNoticia', 'Notícias'), ('ATPasta', 'Pasta'), ('ATInforme', 'Informes'), ('ATLink', 'Links'), ('ATImagem', 'Imagens'), ('ATBanner', 'Banners'), ('ATEvento', 'Eventos'), ('ATAgenda', 'Agendas'), ('ATArquivo', 'Arquivo'), ('ATServico', 'Serviço'), ('ATView', 'Visão')], max_length=20),
        ),
        migrations.AlterField(
            model_name='content',
            name='workflow',
            field=models.CharField(choices=[('Privado', 'Privado'), ('Publico', 'Publico'), ('Revisao', 'Revisão')], default='Privado', max_length=20),
        ),
        migrations.CreateModel(
            name='ContentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('', ''), ('ATPagina', 'Páginas'), ('ATNoticia', 'Notícias'), ('ATInforme', 'Informes'), ('ATLink', 'Links'), ('ATImagem', 'Imagens'), ('ATBanner', 'Banners'), ('ATEvento', 'Eventos'), ('ATAgenda', 'Agendas'), ('ATArquivo', 'Arquivo'), ('ATServico', 'Serviço')], max_length=50)),
                ('path', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_Site.site')),
            ],
            options={
                'verbose_name': 'Regra de conteúdo',
                'verbose_name_plural': 'Regras de conteúdos',
                'db_table': 'catalog_role',
                'ordering': ['content_type'],
                'unique_together': {('site', 'content_type')},
            },
        ),
    ]
