# Generated by Django 5.2.2 on 2026-05-10 02:45

import a_Site.services.imagem_service
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_Content', '0003_alter_content_tipo_alter_content_workflow_and_more'),
        ('a_Site', '0004_alter_contenttype_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoMidia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(max_length=500, upload_to=a_Site.services.imagem_service.ImagemService.content_file_generico)),
                ('titulo', models.CharField(help_text='Nome amigável do arquivo', max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('mimetype', models.CharField(blank=True, editable=False, max_length=100)),
                ('extensao', models.CharField(blank=True, editable=False, max_length=10)),
                ('tamanho', models.PositiveIntegerField(default=0, editable=False, help_text='Tamanho em bytes')),
                ('tipo_geral', models.CharField(choices=[('imagem', 'Imagem'), ('documento', 'Documento'), ('video', 'Vídeo'), ('audio', 'Áudio'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('dono', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='a_Site.site')),
            ],
            options={
                'verbose_name': 'Arquivo de Mídia',
                'verbose_name_plural': 'Arquivos de Mídia',
                'db_table': 'catalog_midia',
                'ordering': ['-create_at'],
            },
        ),
    ]
