# Generated by Django 5.2.2 on 2026-05-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_Content', '0004_arquivomidia'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
