# Generated by Django 5.2.2 on 2026-05-12 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_Content', '0006_event'),
        ('a_Site', '0004_alter_contenttype_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='a_Site.site'),
        ),
    ]
