# Generated by Django 5.2.2 on 2026-05-12 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_Content', '0007_event_site'),
        ('a_Site', '0004_alter_contenttype_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evento', to='a_Content.content'),
        ),
        migrations.AlterField(
            model_name='event',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='a_Site.site'),
        ),
    ]
