# Generated by Django 5.2.2 on 2026-05-12 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_Content', '0008_alter_event_content_alter_event_site'),
        ('a_Site', '0004_alter_contenttype_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='a_Site.site'),
            preserve_default=False,
        ),
    ]
