# Generated by Django 5.2.2 on 2026-05-12 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_Content', '0009_alter_event_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tipo',
            field=models.CharField(default='ATEvento', max_length=20),
        ),
    ]
