# Generated by Django 5.2.2 on 2026-05-12 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_Content', '0010_event_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-inicio'], 'verbose_name': 'Agenda e Evento', 'verbose_name_plural': 'Agendas e Eventos'},
        ),
        migrations.AlterModelTable(
            name='event',
            table='catalog_event',
        ),
    ]
