# Generated by Django 5.2.2 on 2026-05-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_Content', '0011_alter_event_options_alter_event_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='tipo',
            field=models.CharField(choices=[('', ''), ('ATPagina', 'Páginas'), ('ATNoticia', 'Notícias'), ('ATPasta', 'Pasta'), ('ATInforme', 'Informes'), ('ATLink', 'Links'), ('ATImagem', 'Imagens'), ('ATBanner', 'Banners'), ('ATEvento', 'Eventos'), ('ATAgenda', 'Agendas'), ('ATArquivo', 'Arquivo'), ('ATServico', 'Serviço'), ('ATViewer', 'Visão')], max_length=20),
        ),
    ]
