# Generated by Django 5.2.2 on 2026-05-11 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('a_Site', '0004_alter_contenttype_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Criação'), ('update', 'Atualização'), ('delete', 'Exclusão'), ('login', 'Login'), ('logout', 'Logout'), ('publish', 'Publicação'), ('permission', 'Permissão')], max_length=30)),
                ('object_type', models.CharField(help_text='Nome do model afetado', max_length=100)),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('path', models.CharField(blank=True, max_length=500, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='a_Site.site')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'db_table': 'a_log_audit',
                'ordering': ['-create_at'],
                'indexes': [models.Index(fields=['site'], name='a_log_audit_site_id_99fc60_idx'), models.Index(fields=['user'], name='a_log_audit_user_id_ef0f08_idx'), models.Index(fields=['action'], name='a_log_audit_action_84853b_idx'), models.Index(fields=['create_at'], name='a_log_audit_create__1eeaf1_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('login_fail', 'Falha de Login'), ('403', 'Acesso Negado'), ('404', 'Página Não Encontrada'), ('bruteforce', 'Brute Force'), ('blocked', 'Acesso Bloqueado'), ('suspicious', 'Atividade Suspeita'), ('invalid_csrf', 'CSRF Inválido')], max_length=50)),
                ('severity', models.CharField(default='medium', help_text='low, medium, high, critical', max_length=20)),
                ('ip', models.GenericIPAddressField()),
                ('path', models.CharField(blank=True, max_length=500, null=True)),
                ('method', models.CharField(blank=True, max_length=10, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('referer', models.TextField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_bot', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_logs', to='a_Site.site')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Segurança',
                'verbose_name_plural': 'Logs de Segurança',
                'db_table': 'a_log_security',
                'ordering': ['-create_at'],
                'indexes': [models.Index(fields=['event'], name='a_log_secur_event_d25909_idx'), models.Index(fields=['ip'], name='a_log_secur_ip_fc61eb_idx'), models.Index(fields=['user'], name='a_log_secur_user_id_96a092_idx'), models.Index(fields=['create_at'], name='a_log_secur_create__10187f_idx'), models.Index(fields=['severity'], name='a_log_secur_severit_4bb738_idx')],
            },
        ),
        migrations.CreateModel(
            name='StorageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_type', models.CharField(choices=[('media', 'Mídia'), ('backup', 'Backup'), ('temp', 'Temporário')], default='media', max_length=20)),
                ('path', models.CharField(help_text='Caminho monitorado', max_length=500)),
                ('partition_total_gb', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('partition_used_gb', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('partition_free_gb', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('partition_percent_used', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('storage_used_gb', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('storage_percent_used', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_files', models.PositiveBigIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storage_logs', to='a_Site.site')),
            ],
            options={
                'verbose_name': 'Log de Armazenamento',
                'verbose_name_plural': 'Logs de Armazenamento',
                'db_table': 'a_log_storage',
                'ordering': ['-create_at'],
                'indexes': [models.Index(fields=['site'], name='a_log_stora_site_id_5695cf_idx'), models.Index(fields=['storage_type'], name='a_log_stora_storage_5a253e_idx'), models.Index(fields=['create_at'], name='a_log_stora_create__2cd59b_idx')],
            },
        ),
    ]
