# Generated by Django 5.2.2 on 2026-05-11 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_Log', '0001_initial'),
        ('a_Site', '0004_alter_contenttype_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='a_Site.site'),
        ),
    ]
